//! Secrets table access. Two row shapes keep trust boundaries visible in
//! the type system: `SecretMeta` (catalog/detail — no cipher columns) and
//! `SecretCipherRow` (ciphertext + wrapped DEK — fetched exclusively by the
//! scheduler dispatch path). Plaintext values never touch this module.
//! Every mutation writes its immutable audit entry inside the same
//! transaction, and audit metadata never contains a value.

use chrono::{DateTime, Utc};
use sqlx::PgPool;
use uuid::Uuid;

use crate::models::secret::SecretMeta;
use crate::services::secrets_crypto::EncryptedSecret;

fn is_unique_violation(err: &sqlx::Error, constraint: &str) -> bool {
    matches!(
        err,
        sqlx::Error::Database(db)
            if db.is_unique_violation() && db.constraint() == Some(constraint)
    )
}

/// Meta columns + joins shared by the catalog and detail selects.
const META_SELECT: &str = r#"
    SELECT s.id, s.workspace_id, s.repository_id, r.full_name AS repository_name,
           s.name, s.description,
           cu.username AS creator_login, uu.username AS updater_login,
           s.created_at, s.updated_at, s.last_used_at, s.usage_count
    FROM secrets s
    LEFT JOIN repositories r ON r.id = s.repository_id
    LEFT JOIN users cu ON cu.id = s.created_by
    LEFT JOIN users uu ON uu.id = s.updated_by
"#;

pub enum InsertOutcome {
    Created(Box<SecretMeta>),
    DuplicateName,
}

/// Insert a new secret with its ciphertext and audit entry, all or nothing.
/// The id is generated by the caller because it doubles as the AEAD
/// associated data binding the ciphertext to this row.
#[allow(clippy::too_many_arguments)]
pub async fn insert(
    pool: &PgPool,
    id: Uuid,
    workspace_id: Uuid,
    repository_id: Option<Uuid>,
    name: &str,
    description: Option<&str>,
    enc: &EncryptedSecret,
    created_by: Uuid,
    request_id: Option<&str>,
) -> sqlx::Result<InsertOutcome> {
    let mut tx = pool.begin().await?;

    let inserted = sqlx::query(
        r#"
        INSERT INTO secrets
            (id, workspace_id, repository_id, name, description,
             ciphertext, nonce, wrapped_dek, dek_nonce, key_version,
             created_by, updated_by)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $11)
        "#,
    )
    .bind(id)
    .bind(workspace_id)
    .bind(repository_id)
    .bind(name)
    .bind(description)
    .bind(&enc.ciphertext)
    .bind(&enc.nonce)
    .bind(&enc.wrapped_dek)
    .bind(&enc.dek_nonce)
    .bind(enc.key_version)
    .bind(created_by)
    .execute(&mut *tx)
    .await;

    match inserted {
        Ok(_) => {}
        Err(err)
            if is_unique_violation(&err, "secrets_ws_name_key")
                || is_unique_violation(&err, "secrets_repo_name_key") =>
        {
            return Ok(InsertOutcome::DuplicateName);
        }
        Err(err) => return Err(err),
    }

    sqlx::query(
        r#"
        INSERT INTO audit_logs
            (workspace_id, actor_user_id, action, subject_type, subject_id, metadata, request_id)
        VALUES ($1, $2, 'secret.created', 'secret', $3, $4, $5)
        "#,
    )
    .bind(workspace_id)
    .bind(created_by)
    .bind(id)
    .bind(serde_json::json!({
        "name": name,
        "scope": if repository_id.is_some() { "repository" } else { "workspace" },
        "repositoryId": repository_id,
    }))
    .bind(request_id)
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;

    let meta =
        sqlx::query_as::<_, SecretMeta>(&format!("{META_SELECT} WHERE s.id = $1"))
            .bind(id)
            .fetch_one(pool)
            .await?;
    Ok(InsertOutcome::Created(Box::new(meta)))
}

/// Replace the encrypted value wholesale (name and scope are immutable).
/// Returns false when the secret doesn't exist in this workspace.
pub async fn replace_value(
    pool: &PgPool,
    workspace_id: Uuid,
    secret_id: Uuid,
    enc: &EncryptedSecret,
    updated_by: Uuid,
    request_id: Option<&str>,
) -> sqlx::Result<bool> {
    let mut tx = pool.begin().await?;

    let updated: Option<(String,)> = sqlx::query_as(
        r#"
        UPDATE secrets
        SET ciphertext = $3, nonce = $4, wrapped_dek = $5, dek_nonce = $6,
            key_version = $7, updated_by = $8, updated_at = now()
        WHERE workspace_id = $1 AND id = $2
        RETURNING name
        "#,
    )
    .bind(workspace_id)
    .bind(secret_id)
    .bind(&enc.ciphertext)
    .bind(&enc.nonce)
    .bind(&enc.wrapped_dek)
    .bind(&enc.dek_nonce)
    .bind(enc.key_version)
    .bind(updated_by)
    .fetch_optional(&mut *tx)
    .await?;

    let Some((name,)) = updated else {
        return Ok(false);
    };

    sqlx::query(
        r#"
        INSERT INTO audit_logs
            (workspace_id, actor_user_id, action, subject_type, subject_id, metadata, request_id)
        VALUES ($1, $2, 'secret.updated', 'secret', $3, $4, $5)
        "#,
    )
    .bind(workspace_id)
    .bind(updated_by)
    .bind(secret_id)
    .bind(serde_json::json!({ "name": name, "field": "value" }))
    .bind(request_id)
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;
    Ok(true)
}

/// Update the (non-sensitive) description.
pub async fn update_description(
    pool: &PgPool,
    workspace_id: Uuid,
    secret_id: Uuid,
    description: Option<&str>,
    updated_by: Uuid,
    request_id: Option<&str>,
) -> sqlx::Result<bool> {
    let mut tx = pool.begin().await?;

    let updated: Option<(String,)> = sqlx::query_as(
        r#"
        UPDATE secrets
        SET description = $3, updated_by = $4, updated_at = now()
        WHERE workspace_id = $1 AND id = $2
        RETURNING name
        "#,
    )
    .bind(workspace_id)
    .bind(secret_id)
    .bind(description)
    .bind(updated_by)
    .fetch_optional(&mut *tx)
    .await?;

    let Some((name,)) = updated else {
        return Ok(false);
    };

    sqlx::query(
        r#"
        INSERT INTO audit_logs
            (workspace_id, actor_user_id, action, subject_type, subject_id, metadata, request_id)
        VALUES ($1, $2, 'secret.updated', 'secret', $3, $4, $5)
        "#,
    )
    .bind(workspace_id)
    .bind(updated_by)
    .bind(secret_id)
    .bind(serde_json::json!({ "name": name, "field": "description" }))
    .bind(request_id)
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;
    Ok(true)
}

/// Hard-delete with the audit entry in the same transaction. Returns the
/// deleted secret's name, or None if it didn't exist in this workspace.
pub async fn delete(
    pool: &PgPool,
    workspace_id: Uuid,
    secret_id: Uuid,
    actor: Uuid,
    request_id: Option<&str>,
) -> sqlx::Result<Option<String>> {
    let mut tx = pool.begin().await?;

    let deleted: Option<(String, Option<Uuid>)> = sqlx::query_as(
        "DELETE FROM secrets WHERE workspace_id = $1 AND id = $2 RETURNING name, repository_id",
    )
    .bind(workspace_id)
    .bind(secret_id)
    .fetch_optional(&mut *tx)
    .await?;

    let Some((name, repository_id)) = deleted else {
        return Ok(None);
    };

    sqlx::query(
        r#"
        INSERT INTO audit_logs
            (workspace_id, actor_user_id, action, subject_type, subject_id, metadata, request_id)
        VALUES ($1, $2, 'secret.deleted', 'secret', $3, $4, $5)
        "#,
    )
    .bind(workspace_id)
    .bind(actor)
    .bind(secret_id)
    .bind(serde_json::json!({
        "name": name,
        "scope": if repository_id.is_some() { "repository" } else { "workspace" },
        "repositoryId": repository_id,
    }))
    .bind(request_id)
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;
    Ok(Some(name))
}

pub async fn find_meta(
    pool: &PgPool,
    workspace_id: Uuid,
    secret_id: Uuid,
) -> sqlx::Result<Option<SecretMeta>> {
    sqlx::query_as::<_, SecretMeta>(&format!(
        "{META_SELECT} WHERE s.workspace_id = $1 AND s.id = $2"
    ))
    .bind(workspace_id)
    .bind(secret_id)
    .fetch_optional(pool)
    .await
}

/// Validated filters for the catalog list. Every string field is
/// allow-listed or pre-escaped by the handler — never raw input.
pub struct CatalogFilter {
    /// Pre-validated: `workspace` | `repository`.
    pub scope: Option<String>,
    pub repository_id: Option<Uuid>,
    /// Pre-escaped ILIKE pattern matched against name AND description.
    pub search_pattern: Option<String>,
    pub cursor: Option<(DateTime<Utc>, Uuid)>,
    pub limit: i64,
}

/// Keyset-paginated catalog, newest first (artifacts pattern).
pub async fn list_catalog(
    pool: &PgPool,
    workspace_id: Uuid,
    filter: &CatalogFilter,
) -> sqlx::Result<Vec<SecretMeta>> {
    let (cursor_at, cursor_id) = match filter.cursor {
        Some((at, id)) => (Some(at), Some(id)),
        None => (None, None),
    };
    sqlx::query_as::<_, SecretMeta>(&format!(
        r#"
        {META_SELECT}
        WHERE s.workspace_id = $1
          AND ($2::text IS NULL
               OR ($2 = 'workspace'  AND s.repository_id IS NULL)
               OR ($2 = 'repository' AND s.repository_id IS NOT NULL))
          AND ($3::uuid IS NULL OR s.repository_id = $3)
          AND ($4::text IS NULL OR s.name ILIKE $4 ESCAPE '\'
                                OR s.description ILIKE $4 ESCAPE '\')
          AND ($5::timestamptz IS NULL OR (s.created_at, s.id) < ($5, $6))
        ORDER BY s.created_at DESC, s.id DESC
        LIMIT $7
        "#,
    ))
    .bind(workspace_id)
    .bind(&filter.scope)
    .bind(filter.repository_id)
    .bind(&filter.search_pattern)
    .bind(cursor_at)
    .bind(cursor_id)
    .bind(filter.limit.clamp(1, 50))
    .fetch_all(pool)
    .await
}

/// Workspace posture summary in one aggregate pass.
#[derive(Debug, sqlx::FromRow)]
pub struct SecretsSummary {
    pub total: i64,
    pub workspace_scoped: i64,
    pub repository_scoped: i64,
    pub used_last_30d: i64,
    pub never_used: i64,
    pub created_last_30d: i64,
    pub distinct_repositories: i64,
    pub total_injections: i64,
}

pub async fn summary(pool: &PgPool, workspace_id: Uuid) -> sqlx::Result<SecretsSummary> {
    sqlx::query_as::<_, SecretsSummary>(
        r#"
        SELECT COUNT(*)                                                  AS total,
               COUNT(*) FILTER (WHERE repository_id IS NULL)             AS workspace_scoped,
               COUNT(*) FILTER (WHERE repository_id IS NOT NULL)         AS repository_scoped,
               COUNT(*) FILTER (WHERE last_used_at > now() - interval '30 days') AS used_last_30d,
               COUNT(*) FILTER (WHERE last_used_at IS NULL)              AS never_used,
               COUNT(*) FILTER (WHERE created_at > now() - interval '30 days')   AS created_last_30d,
               COUNT(DISTINCT repository_id) FILTER (WHERE repository_id IS NOT NULL) AS distinct_repositories,
               COALESCE(SUM(usage_count), 0)::bigint                     AS total_injections
        FROM secrets
        WHERE workspace_id = $1
        "#,
    )
    .bind(workspace_id)
    .fetch_one(pool)
    .await
}

/// Cipher material for the dispatch path only. Never leaves the scheduler.
#[derive(sqlx::FromRow)]
pub struct SecretCipherRow {
    pub id: Uuid,
    pub name: String,
    pub ciphertext: Vec<u8>,
    pub nonce: Vec<u8>,
    pub wrapped_dek: Vec<u8>,
    pub dek_nonce: Vec<u8>,
    pub key_version: i32,
}

impl SecretCipherRow {
    pub fn encrypted(&self) -> EncryptedSecret {
        EncryptedSecret {
            ciphertext: self.ciphertext.clone(),
            nonce: self.nonce.clone(),
            wrapped_dek: self.wrapped_dek.clone(),
            dek_nonce: self.dek_nonce.clone(),
            key_version: self.key_version,
        }
    }
}

/// All secrets applicable to one repository's pipelines, with precedence
/// baked into SQL: a repository-scoped secret shadows a workspace-scoped
/// secret of the same name (DISTINCT ON keeps the repo row first).
pub async fn resolve_for_dispatch(
    pool: &PgPool,
    workspace_id: Uuid,
    repository_id: Uuid,
) -> sqlx::Result<Vec<SecretCipherRow>> {
    sqlx::query_as::<_, SecretCipherRow>(
        r#"
        SELECT DISTINCT ON (name)
               id, name, ciphertext, nonce, wrapped_dek, dek_nonce, key_version
        FROM secrets
        WHERE workspace_id = $1
          AND (repository_id IS NULL OR repository_id = $2)
        ORDER BY name, (repository_id IS NOT NULL) DESC
        "#,
    )
    .bind(workspace_id)
    .bind(repository_id)
    .fetch_all(pool)
    .await
}

/// Whether any secret applies to this repository — the fail-closed check
/// when the master key is not configured (rows exist that dispatch cannot
/// decrypt).
pub async fn any_for_dispatch(
    pool: &PgPool,
    workspace_id: Uuid,
    repository_id: Uuid,
) -> sqlx::Result<bool> {
    let row: Option<(i32,)> = sqlx::query_as(
        r#"
        SELECT 1 FROM secrets
        WHERE workspace_id = $1 AND (repository_id IS NULL OR repository_id = $2)
        LIMIT 1
        "#,
    )
    .bind(workspace_id)
    .bind(repository_id)
    .fetch_optional(pool)
    .await?;
    Ok(row.is_some())
}

/// Usage telemetry after a successful dispatch. Warn-only at the call site:
/// stats must never fail a dispatch.
pub async fn record_usage(pool: &PgPool, ids: &[Uuid]) -> sqlx::Result<()> {
    if ids.is_empty() {
        return Ok(());
    }
    sqlx::query(
        "UPDATE secrets SET last_used_at = now(), usage_count = usage_count + 1 WHERE id = ANY($1)",
    )
    .bind(ids)
    .execute(pool)
    .await?;
    Ok(())
}

/// Recent secret-subject audit events, optionally narrowed to one secret.
#[derive(Debug, sqlx::FromRow)]
pub struct SecretAuditRow {
    pub action: String,
    pub actor_login: Option<String>,
    pub subject_id: Option<Uuid>,
    pub metadata: serde_json::Value,
    pub created_at: DateTime<Utc>,
}

pub async fn list_audit(
    pool: &PgPool,
    workspace_id: Uuid,
    subject_id: Option<Uuid>,
    limit: i64,
) -> sqlx::Result<Vec<SecretAuditRow>> {
    sqlx::query_as::<_, SecretAuditRow>(
        r#"
        SELECT a.action, u.username AS actor_login, a.subject_id, a.metadata, a.created_at
        FROM audit_logs a
        LEFT JOIN users u ON u.id = a.actor_user_id
        WHERE a.workspace_id = $1 AND a.subject_type = 'secret'
          AND ($2::uuid IS NULL OR a.subject_id = $2)
        ORDER BY a.created_at DESC
        LIMIT $3
        "#,
    )
    .bind(workspace_id)
    .bind(subject_id)
    .bind(limit.clamp(1, 50))
    .fetch_all(pool)
    .await
}
